package:
  name: frontera
  version: "0.4.2"

source:
  fn: frontera-0.4.2.tar.gz
  url: https://pypi.python.org/packages/2c/db/9ff27252459c3bea6a46324028e7420ee3bf2dd9375e7a1239cef9df1204/frontera-0.4.2.tar.gz
  md5: f4d57ef3c30cb39ac62883a14b1f4767

build:
  skip: True  # [py3k]
  number: 0

requirements:
  build:
    - python x.x
    - setuptools
    - six >=1.8.0
    - w3lib >=1.10.0
    - sqlalchemy >=1.0.0

  run:
    - python x.x
    - six >=1.8.0
    - w3lib >=1.10.0
    - sqlalchemy >=1.0.0

test:
  # Python imports
  imports:
    - frontera
    - frontera.core
    - frontera.logger
    - frontera.logger.filters
    - frontera.logger.formatters
    - frontera.logger.handlers
    - frontera.settings
    - frontera.utils
    - frontera.utils.graphs
    - frontera.worker
    - frontera.worker.strategies

about:
  home: https://github.com/scrapinghub/frontera
  license: BSD License
  summary: 'A flexible frontier for web crawlers'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
