package:
  name: dateparser
  version: "0.3.3"

source:
  fn: dateparser-0.3.3.tar.gz
  url: https://pypi.python.org/packages/source/d/dateparser/dateparser-0.3.3.tar.gz
  md5: b27dcf7b018c8b446c1fc30cb6a8bcff
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dateparser = dateparser:main
    #
    # Would create an entry point called dateparser that calls dateparser.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-dateutil >=2.3
    - pyyaml
    - jdatetime
    - umalqurra
    - pytz
    - regex

  run:
    - python
    - python-dateutil >=2.3
    - pyyaml
    - jdatetime
    - umalqurra
    - pytz
    - regex

test:
  # Python imports
  imports:
    - data
    - dateparser
    - dateparser.calendars
    - dateparser.languages

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    #- mock
    #- nose
    #- nose-parameterized
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/scrapinghub/dateparser
  license: BSD License
  summary: 'Date parsing library designed to parse dates from HTML pages'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
