language: python
python: 2.7
sudo: false

env:
  global:
    - PATH=$HOME/miniconda/bin:$PATH
    - CONDA_HOME=$HOME/miniconda
    - BUILD_OUTPUT=$HOME/builds
    # By default use the repository owner as anaconda user.
    - ANACONDA_USER="${ANACONDA_USER:-$(dirname $TRAVIS_REPO_SLUG)}"
    # By default we upload to dev label.
    - ANACONDA_LABEL="${ANACONDA_LABEL:-dev}"
    # The token variable should be set via project settings.
    - ANACONDA_TOKEN="${ANACONDA_TOKEN:-}"

  matrix:
    # We can't use major/minor conda-buildall combination as we want only 2.7 and 3.{4,5}.
    - CONDA_PY=27 CONDA_BUILDALL_MATRIX="python 2.7.*"
    - CONDA_PY=34 CONDA_BUILDALL_MATRIX="python 3.4.*"
    - CONDA_PY=35 CONDA_BUILDALL_MATRIX="python 3.5.*"

install: scripts/conda-setup.sh

script: scripts/conda-build-all.sh

after_success:
  # We anaconda token is available, we attempt to upload to the specified
  # channel. This *MUST* not be executed on PRs.
  - |
    # We need to deactivate virtualenv explicitly to avoid some scripts loading
    # non-conda python interpreter.
    deactivate
    if [ ! -z "$ANACONDA_TOKEN" -a $TRAVIS_PULL_REQUEST = "false" ]; then
      scripts/conda-publish.sh || exit 1
    fi

cache:
  directories:
    - ~/miniconda

notifications:
  email:
    on_success: never
    on_failure: always
