package:
  name: service_identity
  version: "14.0.0"

source:
  fn: service_identity-14.0.0.tar.gz
  url: https://pypi.python.org/packages/source/s/service_identity/service_identity-14.0.0.tar.gz
  md5: cea0b0156d73b025ecef660fb51f0d9a

build:
  number: 0

requirements:
  build:
    - python x.x
    - setuptools
    - characteristic >=14.0.0
    - pyasn1
    - pyasn1-modules
    - pyopenssl >=0.12

  run:
    - python x.x
    - characteristic >=14.0.0
    - pyasn1
    - pyasn1-modules
    - pyopenssl >=0.12

test:
  imports:
    - service_identity

about:
  home: https://github.com/pyca/service_identity
  license: MIT License
  summary: 'Service identity verification for pyOpenSSL.'
