package:
  name: docker-py
  version: "1.7.0"

source:
  fn: docker-py-1.7.0.tar.gz
  url: https://pypi.python.org/packages/f3/64/a26648a02c2a47a12c1c02e40f4bcb51d82ca58b8e4d02d556e2ee649bf3/docker-py-1.7.0.tar.gz
  md5: 987e2bf541afa111e44b3beb668a12af
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - docker-py = docker-py:main
    #
    # Would create an entry point called docker-py that calls docker-py.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python x.x
    - setuptools
    - requests >=2.5.2
    - six >=1.4.0
    - websocket-client >=0.32.0

  run:
    - python x.x
    - requests >=2.5.2
    - six >=1.4.0
    - websocket-client >=0.32.0

test:
  # Python imports
  imports:
    - docker
    - docker.api
    - docker.auth
    - docker.ssladapter
    - docker.unixconn
    - docker.utils
    - docker.utils.ports

about:
  home: https://github.com/docker/docker-py/
  license: Apache Software License
  summary: 'Python client for Docker.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
