package:
  name: flatson
  version: "0.1.0"

source:
  fn: flatson-0.1.0.tar.gz
  url: https://pypi.python.org/packages/source/f/flatson/flatson-0.1.0.tar.gz
  md5: 5a9e6a2ffb3e964419fcbcc49636333b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flatson = flatson:main
    #
    # Would create an entry point called flatson that calls flatson.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - flatson

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/scrapinghub/flatson
  license: BSD License
  summary: 'Tool to flatten stream of JSON-like objects, configured via schema'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
