package:
  name: pydispatcher
  version: "2.0.5"

source:
  fn: PyDispatcher-2.0.5.tar.gz
  url: https://pypi.python.org/packages/source/P/PyDispatcher/PyDispatcher-2.0.5.tar.gz
  md5: 1b9c2ca33580c2770577add7130b0b28

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pydispatch

about:
  home: http://pydispatcher.sourceforge.net
  license: BSD License
  summary: 'Multi-producer-multi-consumer signal dispatching mechanism'
