package:
  name: python-mimeparse
  version: "1.5.2"

source:
  fn: python-mimeparse-1.5.2.tar.gz
  url: https://pypi.python.org/packages/9c/ea/148511af6f5a6889f4d3b90b00e817b4380658fd0def82a85ee83eddfa45/python-mimeparse-1.5.2.tar.gz
  md5: e0e491df099aedc20e05e8a74f1250d8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-mimeparse = python-mimeparse:main
    #
    # Would create an entry point called python-mimeparse that calls python-mimeparse.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/dbtsai/python-mimeparse
  license: MIT License
  summary: 'A module provides basic functions for parsing mime-type names and matching them against a list of media-ranges.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
