package:
  name: scrapy
  version: "1.1.0rc1"

source:
  fn: Scrapy-1.1.0rc1.tar.gz
  url: https://pypi.python.org/packages/source/S/Scrapy/Scrapy-1.1.0rc1.tar.gz
  md5: 79dad4579baf08589d3c69bba611328b

build:
  entry_points:
    - scrapy = scrapy.cmdline:execute
  number: 0

requirements:
  build:
    - python x.x
    - twisted >=10.0.0
    - w3lib >=1.8.0
    - queuelib
    - lxml
    - pyopenssl
    - cssselect >=0.9
    - six >=1.5.2
    - parsel >=0.9.3
    - pydispatcher >=2.0.5
    - service_identity
    - pywin32  # [win]

  run:
    - python x.x
    - twisted >=10.0.0
    - w3lib >=1.8.0
    - queuelib
    - lxml
    - pyopenssl
    - cssselect >=0.9
    - six >=1.5.2
    - parsel >=0.9.3
    - pydispatcher >=2.0.5
    - service_identity
    - pywin32  # [win]

test:
  imports:
    - scrapy

  commands:
    # Ideally, we will run tests here but we require to provide the tests
    # requirements first.
    - scrapy version

about:
  home: http://scrapy.org
  license: BSD License
  summary: 'A high-level Web Crawling and Web Scraping framework'
