package:
  name: scrapy
  version: "1.1.0rc4"

source:
  fn: Scrapy-1.1.0rc4.tar.gz
  url: https://github.com/scrapy/scrapy/archive/1.1.0rc4.tar.gz
  md5: 5edecbf8b9185dcdaeb4a270acb625b3

build:
  entry_points:
    - scrapy = scrapy.cmdline:execute
  number: 0

requirements:
  build:
    - python x.x
    - twisted >=10.0.0
    - w3lib >=1.13.0
    - queuelib
    - lxml
    - pyopenssl
    - cssselect >=0.9
    - six >=1.5.2
    - parsel >=0.9.3
    - pydispatcher >=2.0.5
    - service_identity
    - pywin32  # [win]

  run:
    - python x.x
    - twisted >=10.0.0
    - w3lib >=1.13.0
    - queuelib
    - lxml
    - pyopenssl
    - cssselect >=0.9
    - six >=1.5.2
    - parsel >=0.9.3
    - pydispatcher >=2.0.5
    - service_identity
    - pywin32  # [win]

test:
  imports:
    - scrapy

  commands:
    # Ideally, we will run tests here but we require to provide the tests
    # requirements first.
    - scrapy version

about:
  home: http://scrapy.org
  license: BSD License
  summary: 'A high-level Web Crawling and Web Scraping framework'
