package:
  name: scrapy
  version: "1.0.5"

source:
  fn: Scrapy-1.0.5.tar.gz
  url: https://pypi.python.org/packages/source/S/Scrapy/Scrapy-1.0.5.tar.gz
  md5: b8483fbed91730d30fdf747b2cca8780

build:
  entry_points:
    - scrapy = scrapy.cmdline:execute

  skip: True  # [py3k]

  number: 0

requirements:
  build:
    - python x.x
    - twisted >=10.0.0
    - w3lib >=1.8.0
    - queuelib
    - lxml
    - pyopenssl
    - cssselect >=0.9
    - six >=1.5.2
    - service_identity
    - pywin32  # [win]

  run:
    - python x.x
    - twisted >=10.0.0
    - w3lib >=1.8.0
    - queuelib
    - lxml
    - pyopenssl
    - cssselect >=0.9
    - six >=1.5.2
    - service_identity
    - pywin32  # [win]

test:
  imports:
    - scrapy

  commands:
    # Ideally, we will run tests here but we require to provide the tests
    # requirements first.
    - scrapy version

about:
  home: http://scrapy.org
  license: BSD License
  summary: 'A high-level Web Crawling and Web Scraping framework'
