package:
  name: shub
  version: "2.1.1"

source:
  fn: shub-2.1.1.tar.gz
  url: https://pypi.python.org/packages/ca/2f/344c75a43cae26fe6822d8e477d06940f45dffbd4cf880081221a6607f9c/shub-2.1.1.tar.gz
  md5: 1a8dd60c6a4dc571b43e8e2320a468b0
  patches:
    # We use anaconda's ruamel_yaml and provide a compatiblity patch.
    - ruamel-yaml-compat.patch

build:
  entry_points:
    - shub = shub.tool:cli
  number: 0

requirements:
  build:
    - python x.x
    - setuptools
    - click
    - requests
    - six
    - hubstorage
    - scrapinghub
    - ruamel_yaml

  run:
    - python x.x
    - click
    - requests
    - six
    - hubstorage
    - scrapinghub
    - ruamel_yaml

test:
  imports:
    - shub

  commands:
    - shub --help

about:
  home: http://doc.scrapinghub.com/shub.html
  license: BSD License
  summary: 'Scrapinghub Command Line Client'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
