package:
  name: shub
  version: "2.2.0"

source:
  fn: shub-2.2.0.tar.gz
  url: https://pypi.python.org/packages/0dc/aef4d8416685f0acc06e7bdbeed5130a5dcba16cbae363a19e72c7e496e0/shub-2.2.0.tar.gz
  md5: e3410b87bb044f9dd2a69006f6ea07b2
  patches:
    # We use anaconda's ruamel_yaml and provide a compatiblity patch.
    - ruamel-yaml-compat.patch

build:
  skip: True  # [py3k]
  entry_points:
    - shub = shub.tool:cli
  number: 0

requirements:
  build:
    - python x.x
    - setuptools
    - click
    - requests
    - six
    - hubstorage
    - scrapinghub
    - ruamel_yaml

  run:
    - python x.x
    - click
    - requests
    - six
    - hubstorage
    - scrapinghub
    - ruamel_yaml

test:
  imports:
    - shub

  commands:
    - shub --help

about:
  home: http://doc.scrapinghub.com/shub.html
  license: BSD License
  summary: 'Scrapinghub Command Line Client'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
