package:
  name: jdatetime
  version: "1.7.4"

source:
  fn: jdatetime-1.7.4.tar.gz
  url: https://pypi.python.org/packages/source/j/jdatetime/jdatetime-1.7.4.tar.gz
  md5: 24e7fb2a1a3a6aecfcd5e774b51d9915
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - jdatetime = jdatetime:main
    #
    # Would create an entry point called jdatetime that calls jdatetime.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - jdatetime

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/slashmili/python-jalali
  license: Python Software Foundation License
  summary: 'Jalali datetime binding for python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
