package:
  name: scrapinghub
  version: "1.7.0"

source:
  fn: scrapinghub-1.7.0.tar.gz
  url: https://pypi.python.org/packages/source/s/scrapinghub/scrapinghub-1.7.0.tar.gz
  md5: c7e1ce22f7ce3e2474621a4de23acf95
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scrapinghub = scrapinghub:main
    #
    # Would create an entry point called scrapinghub that calls scrapinghub.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python x.x
    - setuptools
    - requests

  run:
    - python x.x
    - requests

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/scrapinghub/python-scrapinghub
  license: BSD License
  summary: 'Client interface for Scrapinghub API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
