package:
  name: pyasn1-modules
  # We have to stick with this version to avoid having to also build pyasn1 and
  # related dependencies as conda do not have latest pyasn1 required by later
  # pyasn1-modules versions. 
  version: "0.0.5"

source:
  fn: pyasn1-modules-0.0.5.tar.gz
  url: https://pypi.python.org/packages/source/p/pyasn1-modules/pyasn1-modules-0.0.5.tar.gz
  md5: 6c5c9dd61a5784ff22695ac233cb11f8

build:
  number: 0

requirements:
  build:
    - python x.x
    - setuptools
    - pyasn1 >=0.1.4

  run:
    - python x.x
    - pyasn1 >=0.1.4

test:
  imports:
    - pyasn1_modules

about:
  home: http://sourceforge.net/projects/pyasn1/
  license: BSD License
  summary: 'A collection of ASN.1-based protocols modules.'
